stages:
  - deps
  - unit
  - build
  - pack
  - integration

variables:
  GOLANG_VERSION: "1.12.4"
  REPO_GO_DEPS: "goloop/go-deps/${CI_COMMIT_REF_NAME}"
  PYTHON_VERSION: "3.7.3"
  REPO_PY_DEPS: "goloop/py-deps/${CI_COMMIT_REF_NAME}"
  REPO_GOCHAIN: "goloop/gochain/${CI_COMMIT_REF_NAME}"

before_script:
  - env

deps:go:
  image: docker:git
  stage: deps
  script:
    - sh docker/go-deps/build.sh
  tags:
    - docker-build

deps:py:
  image: docker:git
  stage: deps
  script:
    - sh docker/py-deps/build.sh
  tags:
    - docker-build

unit:go:
  image: "${REPO_GO_DEPS}"
  stage: unit
  script:
    - make test
  tags:
    - docker

unit:py:
  image: "${REPO_PY_DEPS}"
  stage: unit
  script:
    - cd pyee
    - python -m unittest -v
  tags:
    - docker

build:pyee:
  image: "${REPO_PY_DEPS}"
  stage: build
  script:
    - cd pyee
    - python3 setup.py bdist_wheel
  artifacts:
    expire_in: 1 day
    paths:
      - pyee/dist/
  tags:
    - docker

.build:go: &build__go
  image: "${REPO_GO_DEPS}"
  stage: build
  variables:
    BUILD_TARGET: all
  script:
    - make ${BUILD_TARGET}
  artifacts:
    expire_in: 1 day
    paths:
      - bin/
  tags:
    - docker

build:gochian:
  <<: *build__go
  script:
    - make gochain

build:goloop:
  <<: *build__go
  script:
    - make goloop

pack:gochian:
  image: docker:git
  stage: pack
  script:
    - sh docker/gochain/build.sh
  tags:
    - docker-build
  dependencies:
    - build:pyee
    - build:gochian

pack:goloop:
  image: docker:git
  stage: pack
  script:
    - sh docker/goloop/build.sh
  tags:
    - docker-build
  dependencies:
    - build:pyee
    - build:goloop

#ITJ : Integration Test Java-sdk
.integration:java-sdk:gochain: &ITJ__gochain
  image: "openjdk:8u212-jdk-alpine"
  stage: integration
  services:
    - ${REPO_GOCHAIN}
  variables:
    GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/config.json"
    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
    GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
  before_script:
    - env
    - cd testsuite
    - sed -i "s/localhost/$(echo ${REPO_GOCHAIN//\//-}|cut -d ":" -f 1)/" $GOCHAIN_ENVFILE
  script:
    - ./gradlew test -DNO_SERVER="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
  after_script:
    - cp -r $GOCHAIN_DATA gochain_data
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - testsuite/.gradle
  artifacts:
    expire_in: 1 day
    when: on_failure
    paths:
      - gochain_data
      - testsuite/build/reports
  tags:
    - docker
  dependencies:
    - pack:gochian
  except:
    - tags

ITJ:gochain:normal:
  <<: *ITJ__gochain
  variables:
    GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/config.json"
    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
    GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
  script:
    - ./gradlew testNormal -DNO_SERVER="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"

ITJ:gochain:governance:
  <<: *ITJ__gochain
  variables:
    GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/govConfig.json"
    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
    GOCHAIN_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_normal.json"
    GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
  script:
    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="false" -DCHAIN_ENV="$GOCHAIN_ENVFILE"

ITJ:gochain:governance:audit:
  <<: *ITJ__gochain
  variables:
    GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/govConfig.json"
    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
    GOCHAIN_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_audit.json"
    GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
  script:
    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
